theme: jekyll-theme-minimal
title: KLM's blog
description: Write ups and stuff
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
